sonar.projectKey=rci-grok
sonar.projectName=rci-grok
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_dd300fb0ff2e827e6ec5fb234e4faa4911d109b3
