sonar.projectKey=tot-gpt
sonar.projectName=tot-gpt
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_3ca13ace88d8bd29d21111a08400ab02908a6312
