sonar.projectKey=0-shot-claude
sonar.projectName=0-shot-claude
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_1bfbd4a2166e7a911a930225d4c14370ea416304
